"""
Final decision layer for the anomaly detection ensemble.

Implements simple and auditable majority voting across model outputs.
"""

import numpy as np
import pandas as pd

from src.utils.logger_utils import logger


def compute_ensemble_decision(df, percentile=95):
    """
    Compute final ensemble score using majority voting.

    For each record, counts how many models (for the selected percentile)
    voted anomaly. The final score is the anomaly vote proportion among
    models that effectively scored that record.

    Args:
        df: DataFrame with all label columns generated by the pipeline.
        percentile: Percentile used in voting (default: 95).
    Returns:
        pd.DataFrame with additional ensemble decision columns.
    """
    p_suffix = f"_p{percentile}_label"
    vote_cols = [c for c in df.columns if c.endswith(p_suffix)]

    if not vote_cols:
        logger.warning(f"Nenhuma coluna de label para p{percentile} encontrada")
        return df

    logger.info("=" * 80)
    logger.info("CAMADA DE DECISAO FINAL DO ENSEMBLE")
    logger.info(f"   Percentil operacional: p{percentile}")
    logger.info(f"   Modelos na votacao: {len(vote_cols)}")
    for col in vote_cols:
        logger.info(f"      - {col}")

    # How many models scored this record (non-NaN labels only)
    df["n_models_scored"] = df[vote_cols].notna().sum(axis=1).astype(int)

    # How many models voted anomaly (NaN ignored by skipna=True)
    df["ensemble_vote_count"] = df[vote_cols].sum(axis=1, skipna=True).astype(int)

    # Vote proportion among scored models
    df["ensemble_vote_pct"] = np.where(
        df["n_models_scored"] > 0,
        df["ensemble_vote_count"] / df["n_models_scored"],
        np.nan,
    )

    # Final alert: majority anomaly (NaN when no model scored)
    df["ensemble_alert"] = np.where(
        df["ensemble_vote_pct"].isna(),
        np.nan,
        (df["ensemble_vote_pct"] >= 0.5).astype(float),
    )

    n_total = len(df)
    n_fully_covered = int((df["n_models_scored"] == len(vote_cols)).sum())
    n_partially_covered = int(
        ((df["n_models_scored"] > 0) & (df["n_models_scored"] < len(vote_cols))).sum()
    )
    n_not_covered = int((df["n_models_scored"] == 0).sum())
    n_alerts = int((df["ensemble_alert"] == 1.0).sum())

    logger.info("=" * 80)
    logger.info("RESULTADO DO ENSEMBLE:")
    logger.info(f"   Total de registros:           {n_total:,}")
    logger.info(
        f"   Avaliados por todos modelos:  {n_fully_covered:,} ({n_fully_covered / n_total * 100:.1f}%)"
    )
    logger.info(
        f"   Avaliados parcialmente:       {n_partially_covered:,} ({n_partially_covered / n_total * 100:.1f}%)"
    )
    logger.info(
        f"   Nao avaliados por nenhum:     {n_not_covered:,} ({n_not_covered / n_total * 100:.1f}%)"
    )
    logger.info(f"   ALERTAS FINAIS (ensemble):    {n_alerts:,} ({n_alerts / n_total * 100:.1f}%)")
    logger.info(f"   NOTA: ensemble_alert=NaN para {n_not_covered:,} registros nao avaliados.")
    logger.info("=" * 80)

    return df


def compute_vehicle_risk_summary(df, placa_col="placa", percentile=95):
    """
    Aggregate ensemble alerts per vehicle for operational ranking.

    Args:
        df: DataFrame with ensemble_alert and ensemble_vote_pct columns.
        placa_col: Vehicle plate column name.
        percentile: Percentile used in final decision (for logging context).
    Returns:
        pd.DataFrame with vehicle risk ranking.
    """
    if "ensemble_alert" not in df.columns:
        raise ValueError("Execute compute_ensemble_decision() antes de chamar esta funcao")

    if placa_col not in df.columns:
        logger.warning(f"Coluna '{placa_col}' nao encontrada. Pulando resumo por veiculo.")
        return pd.DataFrame()

    logger.info(f"Gerando ranking de risco por veiculo usando p{percentile}...")
    vehicle_summary = (
        df.groupby(placa_col)
        .agg(
            total_registros=("ensemble_alert", "count"),
            registros_avaliados=("ensemble_vote_pct", lambda x: x.notna().sum()),
            alertas_ensemble=("ensemble_alert", lambda x: (x == 1.0).sum()),
            score_medio=("ensemble_vote_pct", "mean"),
            score_maximo=("ensemble_vote_pct", "max"),
        )
        .reset_index()
    )

    vehicle_summary["taxa_alerta"] = (
        vehicle_summary["alertas_ensemble"]
        / vehicle_summary["registros_avaliados"].clip(lower=1)
    )

    vehicle_summary = vehicle_summary.sort_values("score_maximo", ascending=False)
    vehicle_summary["ranking_risco"] = range(1, len(vehicle_summary) + 1)

    logger.info(f"Ranking de risco gerado: {len(vehicle_summary)} veiculos analisados")
    top5 = vehicle_summary.head(5)
    for _, row in top5.iterrows():
        logger.info(
            f"   #{int(row['ranking_risco'])} {row[placa_col]}: "
            f"score_max={row['score_maximo']:.3f}, "
            f"alertas={int(row['alertas_ensemble'])}/{int(row['registros_avaliados'])}"
        )
    return vehicle_summary
